services:
  - type: web
    name: hally-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: shuttle.proxy.rlwy.net
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: VNzjzGkacsdAYfXdrorspFDrzSfoTWRR
      - key: DB_NAME
        value: railway
      - key: DB_PORT
        value: "54209"
      - key: MYSQL_PUBLIC_URL
        value: mysql://root:VNzjzGkacsdAYfXdrorspFDrzSfoTWRR@shuttle.proxy.rlwy.net:54209/railway
      - key: PORT
        value: "5001"
